
twist_mux:
  ros__parameters:
    topics:
      joystick  : 
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
      keyboard  : 
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 80